stage('Build/Test') {
    steps {
        echo "Running pytest..."
        sh """
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pytest --maxfail=1 --disable-warnings -q
        """
    }
}
